@host=http://localhost:5240

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjEwNjU2My00ZjM2LTQ4NTktODg5NC1lNTM1YTRhNTg3MDciLCJnaXZlbl9uYW1lIjoiVGhpYWdvIiwiZmFtaWx5X25hbWUiOiJDcnV6IiwianRpIjoiMTRmZGY4NGYtZTVlMC00NzI0LTk2OWMtYjIzMmIxOWVhZmNkIiwiZXhwIjoxNjc1NDU3ODgwLCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.qORhSnUGCrctR3yWkgdKO92pZ7d25fBEvGhEcFTAkAM